# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://danhphan.github.io/bayesian-inferences/"

git_url = "https://github.com/danhphan/bayesian-inferences/tree/master/"

def custom_doc_links(name): return None
